version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: agro-pangolin-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agropangolin
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:15-alpine
    container_name: agro-pangolin-postgres-test
    profiles:
      - test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agro_pangolin_test_db
    ports:
      - '5433:5432'
    volumes:
      - postgres-test-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  postgres-test-data:
