export const PRODUCER_REPOSITORY = Symbol("PRODUCER_REPOSITORY");
export const PRODUCER_READ_REPOSITORY = Symbol("PRODUCER_READ_REPOSITORY");
export const DOCUMENT_VALIDATOR = Symbol("DOCUMENT_VALIDATOR");
